### ISSUE TITLE
[BUG] it does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by dtantono** [Dummerle/Rare#135]
**Describe the bug**
I tried to installed the deb file via terminal/gdebi/Ubuntu Software Installer. But, it does not work

**To Reproduce**
1. Go to https://github.com/Dummerle/Rare/releases/tag/1.7.0
2. Click on (https://github.com/Dummerle/Rare/releases/download/1.7.0/Rare-1.7.0.deb)
3. Download it 
4. Try to installed it and it does not work

**Expected behavior**
as a deb file it should work on Ubuntu

**Screenshots**
![2021-12-03_18-31](https://user-images.githubusercontent.com/29157187/144581037-03252cf5-82c9-4444-ac98-428ae9167330.png)
![2021-12-03_18-44](https://user-images.githubusercontent.com/29157187/144581388-cdff1c11-98ca-48c0-95ee-e00d00c75d85.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 1.7.0
- Installation deb
- Python version: 3.8

**Additional context**

**Error message**
it says error when installing package

**Comment by Dummerle** [comment]
Rare uses a custom version of legendary. Removing legendary should fix it

**Comment by dtantono** [comment]
Hi,
I installed Heroic with Electron and I know original legendary is the main dependency for this. Suppose I remove the original legendary from apt that means heroic will stop working. Is that so?

**Comment by Dummerle** [comment]
I don't know how electron uses legendary. If it runs legendary from python, it will work. If it calls legendary commands it won't. 
I will update bundled legendary, so it will not conflict with other installations

**Comment by dtantono** [comment]
thanks sandboxing is important to ensure that your customised legendary does not make a problem for current and future releases.

**Comment by Dummerle** [comment]
I updated bundled legendary. Now it will not conflict with installed legendary

**Comment by dtantono** [comment]
I downloaded the deb file and the problem persists. So, I think new release is needed

**Comment by Dummerle** [comment]
Yes i will publish a new release, maybe today

**Comment by Dummerle** [comment]
I published a new release with the fixes

**Comment by dtantono** [comment]
yes. But it is not deb file

**Comment by Dummerle** [comment]
The workflow failed. Also the deb file is not optimal. I will check how to improve

**Comment by Dummerle** [comment]
A .deb file is now available

**Comment by dtantono** [comment]
Hi
I checked it and it seems it required pyppresence and I already installed it via pip3. But, it is still does not work.
![2021-12-23_21-01](https://user-images.githubusercontent.com/29157187/147237737-bb8366e2-f073-475c-83f2-d65efa5a3c61.png)
![2021-12-23_21-00](https://user-images.githubusercontent.com/29157187/147237744-cbb9ad09-cf73-4a9d-a7a4-dfd762417968.png)

**Comment by Dummerle** [comment]
What happens if you install it with apt: apt install ./Rare-1.8.3.deb

**Comment by dtantono** [comment]
![image](https://user-images.githubusercontent.com/29157187/147267456-b104cfd2-83e2-4a8c-b724-22ff63345d50.png)
it looks like it does not worked and there is no public release of version 1.8.3. Is that so?

**Comment by Dummerle** [comment]
I will publish the new release, when i am at my pc. I waited for a pull request

**Comment by SomeoneIsWorking** [comment]
![image](https://user-images.githubusercontent.com/9450683/147501851-221fc7b6-1258-4923-95b2-7d0525903b93.png)
I get this error

**Comment by Dummerle** [comment]
> pip install --upgrade https://github.com/Dummerle/Rare/archive/refs/heads/main.zip

This does not work, because the zip file doesn't include legendary submodule. Pypresence is an optional dependency in 1.8.3

**Comment by SomeoneIsWorking** [comment]
> This does not work, because the zip file doesn't include legendary submodule.

But I ran `pip install legendary-gl` separately for that. Is it because the module in it is a custom one?

**Comment by Dummerle** [comment]
The submodule has some adjustments, for example to get download progress.

**Comment by dtantono** [comment]
I tried to install it on KDE Neon for version 1.8.4. It installs well and does not have conflicting dependencies. But, it cannot start

**Comment by Dummerle** [comment]
Do you have logs? Run it with --debug option or send me the content of ~/.cache/rare/logs

**Comment by dtantono** [comment]
hi

here it is 
[Rare_21-12-31--13-52.log](https://github.com/Dummerle/Rare/files/7796077/Rare_21-12-31--13-52.log)
[Rare_21-12-31--20-32.log](https://github.com/Dummerle/Rare/files/7796079/Rare_21-12-31--20-32.log)


![image](https://user-images.githubusercontent.com/29157187/147821272-cab06deb-9796-4a59-be4d-177eb5f5001c.png)

**Comment by Dummerle** [comment]
I don't know, whats the error, but I will try to reproduce it

**Comment by Dummerle** [comment]
I updated the deb file in releases: https://github.com/Dummerle/Rare/releases/download/1.8.4/Rare_1.8.4_fix.deb

Now it should work

**Comment by dtantono** [comment]
I don't think so
[Rare_22-01-03--10-18.log](https://github.com/Dummerle/Rare/files/7800065/Rare_22-01-03--10-18.log)

**Comment by Dummerle** [comment]
I think you qtawesome is too old. Which version is installed?

**Comment by dtantono** [comment]
Hi,
here it is. what do you think?
![image](https://user-images.githubusercontent.com/29157187/147930794-aacec2d2-898f-49cf-8aa7-0a66f2722d69.png)

**Comment by Dummerle** [comment]
0.4.4 is very old. The latest version on pypi is 1.1.1. I will change used icons to get backward compatibility

**Comment by dtantono** [comment]
actually qtawesome is not included in the dependencies required in the deb package and I cannot see in your homepage/documentation that this is required dependency. So, I need to search it manually and I hope you can update this to prevent misunderstanding to the new users.

**Comment by Dummerle** [comment]
python3-qtawesome is included in dependecies. On my Ubuntu test system is python3-qtawesome on version 1.0.2. Do you have an older version of Ubuntu?

**Comment by dtantono** [comment]
maybe your testing system is not the LTS version because I use KDE Neon with LTS kernel and their latest version 0.4.4. 

![image](https://user-images.githubusercontent.com/29157187/147936696-d1da70a8-1518-4891-88e1-cb3ff0a931fe.png)


![image](https://user-images.githubusercontent.com/29157187/147936659-a96d27b5-953d-48a3-9110-53b146d6948f.png)

**Comment by Dummerle** [comment]
I checked it on a virtual environment with 0.4.4 and literally 90% of all icons are broken with this version. 

I have to think about a good solution. You can use appimage, until it doesn't work

**Comment by Dummerle** [comment]
In the new release I replaced some icons. Sometimes it looks a little bit strange, but it works

**Comment by dtantono** [comment]
yes, it works and I will close it
